import type { Publication } from "@/data/publications";

/**
 * Author matching for auto-generating each person's publication list from the
 * shared publications data (single source of truth).
 *
 * The heuristic is "last name + first initial": a person matches a paper if any
 * of its authors has the same surname and the same leading initial. The initial
 * disambiguates same-surname authors (e.g. "Gabriel M" vs "Gabriel HHW").
 *
 * A person can override the derived key via the `authorKey` frontmatter field
 * (e.g. compound surnames, or a citation initial that differs from the display
 * first name). It also takes a list, for people whose name is cited in more
 * than one form (e.g. "Hamdan RA" vs "Abou Hamdan R" vs "Abou-Hamdan R").
 */
export interface AuthorKey {
  last: string;
  initial: string;
}

/**
 * Parse a single cited author token ("Gabriel M", "den Dunnen J",
 * "Braun-Dullaeus R", "Predel H-G") into { last, initial }. The trailing
 * whitespace-separated run of capitals is the initials; the rest is the
 * (possibly multi-word) surname.
 */
export function parseAuthorToken(token: string): AuthorKey | null {
  const m = token.trim().match(/^(.*\S)\s+([A-Z][A-Za-z-]*)$/);
  if (!m) return null;
  return { last: m[1].trim(), initial: m[2][0] };
}

/** All parsed authors of a publication. */
export function citationAuthors(pub: Publication): AuthorKey[] {
  return pub.authors
    .split(/,\s*/)
    .map(parseAuthorToken)
    .filter((a): a is AuthorKey => a !== null);
}

/**
 * Derive a person's match keys from their display name, or from an explicit
 * override (a single citation form or a list of them).
 */
export function personAuthorKeys(
  name: string,
  override?: string | string[]
): AuthorKey[] {
  if (override) {
    const forms = Array.isArray(override) ? override : [override];
    return forms.map(parseAuthorToken).filter((k): k is AuthorKey => k !== null);
  }
  const parts = name.trim().split(/\s+/);
  if (parts.length < 2) return [];
  return [{ last: parts[parts.length - 1], initial: parts[0][0] }];
}

/** Publications a person (co-)authored, newest first. */
export function publicationsForPerson(
  pubs: Publication[],
  name: string,
  override?: string | string[]
): Publication[] {
  const keys = personAuthorKeys(name, override);
  if (keys.length === 0) return [];
  return pubs
    .filter((p) =>
      citationAuthors(p).some((a) =>
        keys.some((key) => a.last === key.last && a.initial === key.initial)
      )
    )
    .slice()
    .sort((a, b) => b.year - a.year);
}

/** Shape a publication for the <Person> `publications.items` list. */
export function toPersonItem(pub: Publication) {
  return {
    text: `${pub.authors} (${pub.year}). ${pub.body}`,
    href: pub.url,
    linkText: pub.linkText,
  };
}

/**
 * Resolve a person's Publications section. A manual `publications` block in the
 * frontmatter (e.g. Christian Puta's link to /publications) takes precedence
 * and disables auto-generation; otherwise the list is generated by matching.
 * In both cases the section carries a `count` of the person's matched papers,
 * so the disclosure pill reflects the true publication total rather than the
 * number of rendered items (which, for a manual link, is just 1).
 * Returns `undefined` when the person has no publications to show.
 */
export function personPublications(
  pubs: Publication[],
  data: { name: string; authorKey?: string | string[]; publications?: unknown }
) {
  const matched = publicationsForPerson(pubs, data.name, data.authorKey);
  if (data.publications) {
    return matched.length > 0
      ? { ...(data.publications as object), count: matched.length }
      : data.publications;
  }
  const items = matched.map(toPersonItem);
  return items.length > 0 ? { items } : undefined;
}
