import type { Publication } from "@/data/publications";

/**
 * Author matching for auto-generating each person's publication list from the
 * shared publications data (single source of truth).
 *
 * The heuristic is "last name + first initial": a person matches a paper if any
 * of its authors has the same surname and the same leading initial. The initial
 * disambiguates same-surname authors (e.g. "Gabriel M" vs "Gabriel HHW").
 *
 * A person can override the derived key via the `authorKey` frontmatter field
 * (e.g. compound surnames, or a citation initial that differs from the display
 * first name).
 */
export interface AuthorKey {
  last: string;
  initial: string;
}

/**
 * Parse a single cited author token ("Gabriel M", "den Dunnen J",
 * "Braun-Dullaeus R", "Predel H-G") into { last, initial }. The trailing
 * whitespace-separated run of capitals is the initials; the rest is the
 * (possibly multi-word) surname.
 */
export function parseAuthorToken(token: string): AuthorKey | null {
  const m = token.trim().match(/^(.*\S)\s+([A-Z][A-Za-z-]*)$/);
  if (!m) return null;
  return { last: m[1].trim(), initial: m[2][0] };
}

/** All parsed authors of a publication. */
export function citationAuthors(pub: Publication): AuthorKey[] {
  return pub.authors
    .split(/,\s*/)
    .map(parseAuthorToken)
    .filter((a): a is AuthorKey => a !== null);
}

/** Derive a person's match key from their display name, or an explicit override. */
export function personAuthorKey(name: string, override?: string): AuthorKey | null {
  if (override) return parseAuthorToken(override);
  const parts = name.trim().split(/\s+/);
  if (parts.length < 2) return null;
  return { last: parts[parts.length - 1], initial: parts[0][0] };
}

/** Publications a person (co-)authored, newest first. */
export function publicationsForPerson(
  pubs: Publication[],
  name: string,
  override?: string
): Publication[] {
  const key = personAuthorKey(name, override);
  if (!key) return [];
  return pubs
    .filter((p) =>
      citationAuthors(p).some((a) => a.last === key.last && a.initial === key.initial)
    )
    .slice()
    .sort((a, b) => b.year - a.year);
}

/** Shape a publication for the <Person> `publications.items` list. */
export function toPersonItem(pub: Publication) {
  return {
    text: `${pub.authors} (${pub.year}). ${pub.body}`,
    href: pub.url,
    linkText: pub.linkText,
  };
}

/**
 * Resolve a person's Publications section. A manual `publications` block in the
 * frontmatter (e.g. Christian Puta's link to /publications) takes precedence
 * and disables auto-generation; otherwise the list is generated by matching.
 * Returns `undefined` when the person has no publications to show.
 */
export function personPublications(
  pubs: Publication[],
  data: { name: string; authorKey?: string; publications?: unknown }
) {
  if (data.publications) return data.publications;
  const items = publicationsForPerson(pubs, data.name, data.authorKey).map(toPersonItem);
  return items.length > 0 ? { items } : undefined;
}
